name: 'Publish docs with Confluenza'
description: 'Publish docs with Confluenza solo template'
author: "Jeroen Knoops"
branding:
  icon: "activity"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Create public folder
      run: $GITHUB_ACTION_PATH/.github/bin/create-pages.sh
      shell: bash
