name: GH Pages

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-pages:
    name: Deploy GH-pages
    runs-on: ubuntu-latest

    steps:
    - name: Check out code 🛎️
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
    - name: Create confluenza pages 📦 
      uses: confluenza/confluenza-action@main
      env:
        PREFIX_PATH: true
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: public
        CLEAN: true
